---
title: "Homework 2"
author: "Matthew Borelli & Isaac Hulsey"
date: "2/2/2020"
output: md_document
---

```{r data, include=FALSE}
library(readr)
# setwd("D:/Documents/MA_Econ/Spring/ECO395M/My Work/Homework/ECO395M_HW2")
brca = read.csv("D:/Documents/MA_Econ/Spring/ECO395M/My Work/Homework/ECO395M_HW2/data/brca.csv")
online_news = read.csv("D:/Documents/MA_Econ/Spring/ECO395M/My Work/Homework/ECO395M_HW2/data/online_news.csv")
```

# A Hospital Audit

## Introduction

The main goal of this statistical analysis is to audit the performance of your radiologists for mammogram screenings. Each doctor wants to limit the amount of false positives and false negatives as much as possible, but mammograms are not perfect. Therefore, it is reasonable to not expect 100% accuracy from your radiologists. However, we can utilize statistical analyses in order to see how efficient the radiologists are at recalling patients. Using the data you provided, approximately 1000 mammogram screenings from five randomly selected radiologists, we want to examing two important questions for you:

- Are some radiologists more clinically conservative than others in recalling patients, holding patient risk factors equal?
- When the radiologists at this hospital interpret a mammogram to make a decision on whether to recall the patient, does the data suggest that they should be weighing some clinical risk factors more heavily than they currently are?

